apiVersion: netbox.thibaultbustarret-ovhcloud.com/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: netbox-creds
      namespace: crossplane-system
      key: credentials
