// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DeviceTypeInitParameters struct {

	// (Boolean)
	IsFullDepth *bool `json:"isFullDepth,omitempty" tf:"is_full_depth,omitempty"`

	// (String)
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (String)
	PartNumber *string `json:"partNumber,omitempty" tf:"part_number,omitempty"`

	// (String)
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (Set of String)
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Defaults to 1.0.
	// Defaults to `1.0`.
	UHeight *float64 `json:"uHeight,omitempty" tf:"u_height,omitempty"`
}

type DeviceTypeObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean)
	IsFullDepth *bool `json:"isFullDepth,omitempty" tf:"is_full_depth,omitempty"`

	// (Number)
	ManufacturerID *float64 `json:"manufacturerId,omitempty" tf:"manufacturer_id,omitempty"`

	// (String)
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (String)
	PartNumber *string `json:"partNumber,omitempty" tf:"part_number,omitempty"`

	// (String)
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (Set of String)
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Defaults to 1.0.
	// Defaults to `1.0`.
	UHeight *float64 `json:"uHeight,omitempty" tf:"u_height,omitempty"`
}

type DeviceTypeParameters struct {

	// (Boolean)
	// +kubebuilder:validation:Optional
	IsFullDepth *bool `json:"isFullDepth,omitempty" tf:"is_full_depth,omitempty"`

	// (Number)
	// +crossplane:generate:reference:type=Manufacturer
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ManufacturerID *float64 `json:"manufacturerId,omitempty" tf:"manufacturer_id,omitempty"`

	// Reference to a Manufacturer to populate manufacturerId.
	// +kubebuilder:validation:Optional
	ManufacturerIDRef *v1.Reference `json:"manufacturerIdRef,omitempty" tf:"-"`

	// Selector for a Manufacturer to populate manufacturerId.
	// +kubebuilder:validation:Optional
	ManufacturerIDSelector *v1.Selector `json:"manufacturerIdSelector,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	PartNumber *string `json:"partNumber,omitempty" tf:"part_number,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (Set of String)
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Defaults to 1.0.
	// Defaults to `1.0`.
	// +kubebuilder:validation:Optional
	UHeight *float64 `json:"uHeight,omitempty" tf:"u_height,omitempty"`
}

// DeviceTypeSpec defines the desired state of DeviceType
type DeviceTypeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DeviceTypeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DeviceTypeInitParameters `json:"initProvider,omitempty"`
}

// DeviceTypeStatus defines the observed state of DeviceType.
type DeviceTypeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DeviceTypeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// DeviceType is the Schema for the DeviceTypes API. From the official documentation https://docs.netbox.dev/en/stable/features/device-types/#device-types_1: A device type represents a particular make and model of hardware that exists in the real world. Device types define the physical attributes of a device (rack height and depth) and its individual components (console, power, network interfaces, and so on).
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,netbox}
type DeviceType struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.model) || (has(self.initProvider) && has(self.initProvider.model))",message="spec.forProvider.model is a required parameter"
	Spec   DeviceTypeSpec   `json:"spec"`
	Status DeviceTypeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DeviceTypeList contains a list of DeviceTypes
type DeviceTypeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DeviceType `json:"items"`
}

// Repository type metadata.
var (
	DeviceType_Kind             = "DeviceType"
	DeviceType_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DeviceType_Kind}.String()
	DeviceType_KindAPIVersion   = DeviceType_Kind + "." + CRDGroupVersion.String()
	DeviceType_GroupVersionKind = CRDGroupVersion.WithKind(DeviceType_Kind)
)

func init() {
	SchemeBuilder.Register(&DeviceType{}, &DeviceTypeList{})
}
