// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ManufacturerInitParameters struct {

	// (String)
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

type ManufacturerObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

type ManufacturerParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

// ManufacturerSpec defines the desired state of Manufacturer
type ManufacturerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ManufacturerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManufacturerInitParameters `json:"initProvider,omitempty"`
}

// ManufacturerStatus defines the observed state of Manufacturer.
type ManufacturerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManufacturerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Manufacturer is the Schema for the Manufacturers API. From the official documentation https://docs.netbox.dev/en/stable/features/device-types/#manufacturers: A manufacturer represents the "make" of a device; e.g. Cisco or Dell. Each device type must be assigned to a manufacturer. (Inventory items and platforms may also be associated with manufacturers.) Each manufacturer must have a unique name and may have a description assigned to it.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,netbox}
type Manufacturer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ManufacturerSpec   `json:"spec"`
	Status            ManufacturerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManufacturerList contains a list of Manufacturers
type ManufacturerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Manufacturer `json:"items"`
}

// Repository type metadata.
var (
	Manufacturer_Kind             = "Manufacturer"
	Manufacturer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Manufacturer_Kind}.String()
	Manufacturer_KindAPIVersion   = Manufacturer_Kind + "." + CRDGroupVersion.String()
	Manufacturer_GroupVersionKind = CRDGroupVersion.WithKind(Manufacturer_Kind)
)

func init() {
	SchemeBuilder.Register(&Manufacturer{}, &ManufacturerList{})
}
