apiVersion: dcim.thibaultbustarret-ovhcloud.com/v1alpha1
kind: Manufacturer
metadata:
  annotations:
    meta.upbound.io/example-id: dcim/v1alpha1/manufacturer
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider: {}
