/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	resource "github.com/crossplane/upjet/pkg/resource"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/thibaultbustarret-ovhcloud/provider-netbox/apis/dcim/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this IPAddress.
func (mg *IPAddress) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.DeviceInterfaceID),
		Extract:      resource.ExtractResourceID(),
		Reference:    mg.Spec.ForProvider.DeviceInterfaceIDRef,
		Selector:     mg.Spec.ForProvider.DeviceInterfaceIDSelector,
		To: reference.To{
			List:    &v1alpha1.DeviceInterfaceList{},
			Managed: &v1alpha1.DeviceInterface{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DeviceInterfaceID")
	}
	mg.Spec.ForProvider.DeviceInterfaceID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DeviceInterfaceIDRef = rsp.ResolvedReference

	return nil
}
